on: [push]
name: build
jobs:
  stack_tests:
    name: Stack Tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
      - run: |
          mkdir ~/.stack
          echo "allow-newer: true" >> ~/.stack/config.yaml
          stack test --ghc-options=-O2
